# Set version information in a config.h file
set(DMS3_CHIP8_VERSION_MAJOR 0)
set(DMS3_CHIP8_VERSION_MINOR 1)
set(DMS3_CHIP8_PATCH 1)
set(DMS3_CHIP8_BUILD 1)
set(DMS3_CHIP8_COMMIT "$Revision: $")
set(DMS3_CHIP8_VERSION ${DMS3_CHIP8_VERSION_MAJOR}.${DMS3_CHIP8_VERSION_MINOR}.${DMS3_CHIP8_PATCH})
